server:
  port: 8031

spring:
  application:
    name: BANKAPI
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12715363
    password: lgL1fRfhQd
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sql12715363

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
  config:
    import: optional:file:.env[.properties]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.web:
          FilterChainProxy: DEBUG
          access:
            ExceptionTranslationFilter: DEBUG
            intercept:
              FilterSecurityInterceptor: DEBUG
          authentication:
            UsernamePasswordAuthenticationFilter: DEBUG
          firewall: DEBUG
      hibernate.sql: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
openapi:
  title: Bank API Document
  version: 2.0
  description : Bank API Service
  serverURL :
  serverName : serverTest