server:
  port: 8031

spring:
  application:
    name: BANKAPI
  datasource:
    url: jdbc:postgresql://hiep-michael-7070.6xw.aws-ap-southeast-1.cockroachlabs.cloud:26257/BankDATABASE?sslmode=verify-full
    username: hiep
    password: 6F3u_EmyXaQscJ9JmG-Yjw
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:file:.env[.properties]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: pro

logging:
  level:
    org:
      springframework:
        security: DEBUG
        security.web:
          FilterChainProxy: DEBUG
          access:
            ExceptionTranslationFilter: DEBUG
            intercept:
              FilterSecurityInterceptor: DEBUG
          authentication:
            UsernamePasswordAuthenticationFilter: DEBUG
          firewall: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
openapi:
  title: Bank API Document
  version: 2.0
  description : Bank API Service
  serverURL :
  serverName : serverTest
